### ISSUE TITLE
How to solve/change this piece of code using cxsparse. TIA

### ISSUE THREAD

**Issue by hsingla94** [PetterS/CXSparse#2]
How to solve/change this piece of code using cxsparse.

          	SparseMatrix<double> A(cInd, kVar);
        
		A.setFromTriplets(triplets.begin(), triplets.end());

		Eigen::SPQR<SparseMatrix<double> > solver(A)
		VectorXd res = solver.solve(B.block(0,0,cInd,1));

Thanks ! cheers

**Comment by PetterS** [comment]
I don’t know.
